export enum WeatherConditions {
  FOGGY = "foggy",
  SUNNY = "sunny",
  RAINY = "rainy",
  CLOUDY = "cloudy",
  DESCRIPTION_FOGGY = "Foggy",
  DESCRIPTION_SUNNY = "Sunny",
  DESCRIPTION_RAINY = "Rainy",
  DESCRIPTION_CLOUDY = "Cloudy",
  DESCRIPTION_CLEAR = "Clear",

  WEATHER_FOG = "fog",
  WEATHER_FOGGY = "foggy",
  WEATHER_MIST = "mist",
  WEATHER_RAIN = "rain",
  WEATHER_DRIZZLE = "drizzle",
  WEATHER_SHOWER = "shower",
  WEATHER_CLEAR = "clear",
  WEATHER_SUN = "sun",
  WEATHER_CLOUD = "cloud",
  WEATHER_OVERCAST = "overcast",
  WEATHER_SNOW = "snow",
  WEATHER_FLURRY = "flurr",
  WEATHER_THUNDER = "thunder",
  WEATHER_STORM = "storm",
}
