export const ENV_CONSTANTS = {
  APP_API_URL: process.env.REACT_APP_API_URL,
  API_GOOGLE_AUTH: process.env.REACT_APP_API_GOOGLE_AUTH,
  GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
  GOOGLE_AUTH: process.env.REACT_APP_API_GOOGLE_AUTH,
  GOOGLE_SCOPE: process.env.REACT_APP_API_GOOGLE_SCOPE,
  OPEN_WEATHER_TOKEN: process.env.REACT_APP_OPEN_WEATHER_TOKEN,
};
